name: Tests

on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        neovim: [stable, nightly]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}
    
    - name: Install dependencies
      run: |
        make deps
    
    - name: Run tests
      run: |
        make test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.neovim }}
        path: test-results/
        if-no-files-found: ignore
    
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-results-${{ matrix.os }}-${{ matrix.neovim }}
        path: test-results/junit.xml
        if-no-files-found: ignore